# uses the brooklyn-spark node
name: Example App AWS

location: jclouds:aws-ec2:eu-west-1

services:
- type: org.apache.brooklyn.entity.stock.BasicApplication
  id: app

  brooklyn.children:
  - type: org.apache.brooklyn.entity.group.DynamicCluster
    description: An Apache Spark cluster
    name: Spark Cluster
    id: spark-cluster
    brooklyn.config:
      cluster.initial.size: 3

    firstMemberSpec:
      $brooklyn:entitySpec:
        type: spark-node
        name: Spark Master
        id: spark-master
        brooklyn.config:
          provisioning.properties:
            customizers:
            - $brooklyn:object:
                type: org.apache.brooklyn.location.jclouds.networking.SharedLocationSecurityGroupCustomizer
                object.fields:
                  tcpPortRanges: ["22","4040-4050","6066","8080","8081"]
        brooklyn.children:
        - type: spark-application
          name: SparkPi
          brooklyn.config:
            spark.app.class: "org.apache.spark.examples.SparkPi"
            spark.app.jar: "http://dl.bintray.com/typesafe/maven-releases/org/apache/spark/spark-examples_2.11/1.6.0-typesafe-001/spark-examples_2.11-1.6.0-typesafe-001.jar"

    memberSpec:
      $brooklyn:entitySpec:
        type: spark-node
        name: Spark Worker
        id: spark-worker
        brooklyn.config:
          spark.master.url: $brooklyn:entity("spark-master").attributeWhenReady("spark.url")
          provisioning.properties:
            customizers:
            - $brooklyn:object:
                type: org.apache.brooklyn.location.jclouds.networking.SharedLocationSecurityGroupCustomizer
                object.fields:
                  tcpPortRanges: ["22","4040-4050","6066","8080"]
