# uses the brooklyn-spark node
name: Example App

location: jclouds:aws-ec2:eu-west-1

services:
- type: org.apache.brooklyn.entity.stock.BasicApplication
  id: app

  brooklyn.children:
  - type: org.apache.brooklyn.entity.group.DynamicCluster
    description: An Apache Spark cluster
    name: Spark Cluster
    id: spark-cluster
    brooklyn.config:
      cluster.initial.size: 3

    firstMemberSpec:
      $brooklyn:entitySpec:
        type: spark-node
        name: Spark Master
        id: spark-master

    memberSpec:
      $brooklyn:entitySpec:
        type: spark-node
        name: Spark Worker
        id: spark-worker
        brooklyn.config:
          spark.master.url: $brooklyn:entity("spark-master").attributeWhenReady("spark.url")
        brooklyn.children:
          - type: spark-application
          - type: spark-application
            brooklyn.config:
              spark.app.class: "org.apache.spark.examples.SparkTC"